import type { Portfolio } from './types.js';

export const seedPortfolios: Portfolio[] = [
	{
		id: '1',
		name: 'Langfrist-Depot',
		description: 'Langfristige Buy-and-Hold Strategie mit Fokus auf Qualitätsaktien und ETFs.',
		tags: ['Value', 'Buy & Hold'],
		currency: 'EUR',
		createdAt: '2024-01-15T10:00:00.000Z',
		updatedAt: '2024-11-20T14:30:00.000Z',
		holdings: [
			{
				id: 'h1',
				symbol: 'AAPL',
				name: 'Apple Inc.',
				assetType: 'stock',
				quantity: 25,
				buyPrice: 142.5,
				currency: 'USD',
				buyDate: '2023-03-10',
				exchange: 'NASDAQ',
				isin: 'US0378331005',
			},
			{
				id: 'h2',
				symbol: 'MSFT',
				name: 'Microsoft Corp.',
				assetType: 'stock',
				quantity: 10,
				buyPrice: 310.0,
				currency: 'USD',
				buyDate: '2023-06-01',
				exchange: 'NASDAQ',
				isin: 'US5949181045',
			},
			{
				id: 'h3',
				symbol: 'VWCE',
				name: 'Vanguard FTSE All-World UCITS ETF',
				assetType: 'etf',
				quantity: 50,
				buyPrice: 98.2,
				currency: 'EUR',
				buyDate: '2022-09-15',
				exchange: 'XETRA',
				isin: 'IE00B3RBWM25',
			},
		],
	},
	{
		id: '2',
		name: 'Krypto-Portfolio',
		description: 'Spekulativer Anteil mit Krypto-Assets.',
		tags: ['Krypto', 'Spekulativ'],
		currency: 'EUR',
		createdAt: '2024-03-01T08:00:00.000Z',
		updatedAt: '2024-12-01T09:15:00.000Z',
		holdings: [
			{
				id: 'h4',
				symbol: 'BTC',
				name: 'Bitcoin',
				assetType: 'crypto',
				quantity: 0.35,
				buyPrice: 42000,
				currency: 'USD',
				buyDate: '2024-01-10',
			},
			{
				id: 'h5',
				symbol: 'ETH',
				name: 'Ethereum',
				assetType: 'crypto',
				quantity: 2.5,
				buyPrice: 2200,
				currency: 'USD',
				buyDate: '2024-02-20',
			},
		],
	},
	{
		id: '3',
		name: 'Dividenden-Depot',
		description: 'Fokus auf dividendenstarke Aktien für passives Einkommen.',
		tags: ['Dividende', 'Einkommen'],
		currency: 'EUR',
		createdAt: '2023-08-10T12:00:00.000Z',
		updatedAt: '2024-10-05T16:00:00.000Z',
		holdings: [
			{
				id: 'h6',
				symbol: 'ALV',
				name: 'Allianz SE',
				assetType: 'stock',
				quantity: 20,
				buyPrice: 220.0,
				currency: 'EUR',
				buyDate: '2023-08-10',
				exchange: 'XETRA',
				isin: 'DE0008404005',
			},
			{
				id: 'h7',
				symbol: 'DTE',
				name: 'Deutsche Telekom AG',
				assetType: 'stock',
				quantity: 100,
				buyPrice: 19.5,
				currency: 'EUR',
				buyDate: '2023-09-01',
				exchange: 'XETRA',
				isin: 'DE0005557508',
			},
		],
	},
];

/** Loads seed data into localStorage (overwrites existing data). */
export function loadSeedData(): void {
	localStorage.setItem('portfolios', JSON.stringify(seedPortfolios));
}
